services:
  db:
    image: 'postgres:14.17-alpine'
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - dev_db_data:/var/lib/postgresql/data


volumes:
  dev_db_data: